run:
  go: '1.23'
  timeout: 5m

linters:
  disable-all: true
  enable:
    - revive
    - govet
    - unused
    - ineffassign
    - typecheck
    - goconst
    - copyloopvar
    - staticcheck
    - gosimple
    - unconvert
    - goconst
    - goimports
    - misspell
    - unparam
    - err113
    - prealloc
    - gocritic
    - gosec
    - errorlint
    - godot
    - paralleltest
    - wastedassign
    - tagliatelle

linters-settings:
  govet:
    enable-all: true
    disable:
      - shadow

issues:
  exclude-use-default: false
  exclude-rules:
    - path: (.+)_test.go
      linters:
        - govet
