version: "2"
run:
  go: "1.24"
linters:
  enable:
    - copyloopvar
    - err113
    - errorlint
    - goconst
    - gocritic
    - godot
    - gosec
    - misspell
    - paralleltest
    - prealloc
    - revive
    - tagliatelle
    - unconvert
    - unparam
    - wastedassign
  settings:
    govet:
      disable:
        - shadow
      enable-all: true
  exclusions:
    generated: lax
    rules:
      - linters:
          - govet
        path: (.+)_test.go
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
