on:
  push:
    tags:
      - 'v*'

env:
  GO_VERSION: "1.23.2"

name: Upload release assets after tagging
jobs:
  build:
    name: create assets
    runs-on: self-hosted
    steps:
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@90a3faa9d0182683851fbfa97ca1a2cb983bfca3 #v6
        with:
          version: v2
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}